Name: Rollstation radio
Admin: admin@site.com
Location: Saint Petersburg
UsesI2P: true
DisableClearnet: true
Host: 127.0.0.1
Socket:
  Port: 8008

Limits:
  Clients: 100000
  Sources: 5
  SourceIdleTimeOut: 10
  EmptyBufferIdleTimeOut: 5
  WriteTimeOut: 10

Auth:
  AdminPassword: admin

Paths:
  Log: log/
  Web: html/

Logging:
  LogLevel: 4
  LogSize: 50000
  UseMonitor: true
  MonitorInterval: 5
  UseStat: true
  StatInterval: 5

Mounts:
  - Name: RockRadio96
    User: admin
    Password: admin
    Genre: Rock
    Description: Rock radio station, Saint Petersburg
    BitRate: 96
    BurstSize: 65535
    DumpFile:

  - Name: JazzMe
    User: admin
    Password: admin
    Genre: Jazz
    Description: Indie jazz radio station, Online cast
    BitRate: 128
    BurstSize: 65535
    DumpFile: